module.exports = {
    INVALID_CREDENTIALS: 'Email or password is incorrect',
    INTERNAL_SERVER_ERROR: 'Internal server error.',
    REQUIRED_DATA: 'Please fill all required data.',
    SUCCESSFULLY_DONE: 'Data found successfully.',
    WENT_WRONG: 'Something went wrong',
    SAVED_SUCCESSFULLY: "is saved successfully.",
    NOT_MATCH: "Email id  does not exist.",
    LOGIN_SUCCESS: "Login successfully.",
    NOT_FOUND: "No data found.",
    UPDATE: " is updated successfully.",
    DELETE: " deleted successfully.",
    USER_NOT_FOUND: "User not found.",
    ALL_READY_EXIST: ' already exist.',
    TYPE_NOT_FOUND: ' not found',
    USER_NOT_VERIFIED: ' User is not verified',
    LIMIT_EXCEED: "Product qantity limit exceed",
    ORDER_SUCCESS: "Your order is placed successfully",
    INVALID_TOKEN:"Provided token is invalid",
    INVALID_AUTH:"Authentication error",
};